name: release

on:
  [push, release]

jobs:
  build-dist-artefacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          python -m pip install build
          python -m build
          ls -althF dist
