name: test-docker-image

on:
  [ push, pull_request ]

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build test environment
        working-directory: docker/tests
        run: |
          docker compose build
      - name: Run containers
        working-directory: docker/tests
        run: |
          docker compose up -d
      - name: Run tests
        run: |
          # test adding a subscription
          docker exec subscriber wis2downloader add-subscription --topic cache/a/wis2/+/services/# 
          # test listing subscriptions
          docker exec subscriber wis2downloader list-subscriptions
          # publish a test message
          docker exec publisher pywis-pubsub publish --topic cache/a/wis2/my-centre/services/downloader \
            --config /pywis-pubsub/config/config.yml \
            -i test -u "http://subscriber:5000/openapi"
          sleep 1s
          # cat file contents
          cat ./data/downloads/`date +"%Y"`/`date +"%m"`/`date +"%d"`/cache/a/wis2/my-centre/services/downloader/openapi.bin
          # test deleting subscriptions
          docker exec subscriber wis2downloader remove-subscription --topic cache/a/wis2/+/services/# 

      - name: Shutdown
        working-directory: docker/tests
        run: |
          docker compose down