name: test-docker-image

on:
  [ push, pull_request ]

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build test environment
        run: |
          pwd
          ls
          cd wis2-downloader/docker/tests
          docker compose build
      - name: Run containers
        run: |
          docker compose up -d
      - name: Run tests
        run: |
          docker exec subscriber wis2downloader list-subscriptions
      - name: Shutdown
        run: |
          docker compose down