name: Run Trivy vulnerability scanner

on: [ push ]

permissions:
  contents: read
  packages: write
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build wis2downloader
        run: |
          docker build -t wis2downloader:test -f ./docker/Dockerfile .
      - name: Run Trivy vulnerability scanner on wis2downloader
        uses: aquasecurity/trivy-action@0.20.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: 'wis2downloader:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignorefile: '.trivyignore'