# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: publish image to ghcr.io

on:
  push:
    branches:
      - main
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=pep440,pattern={{version}}

      - name: Create Dockerfile
        run: |
          echo "FROM python:3.9-slim" > Dockerfile
          echo "EXPOSE 8080" >> Dockerfile
          echo "ENV DOWNLOAD_DIR /app/downloads" >> Dockerfile
          echo "ENV RETENTION_PERIOD_HOURS 24" >> Dockerfile
          echo "ENV BROKER_URL \"globalbroker.meteo.fr\"" >> Dockerfile
          echo "ENV BROKER_PORT 443" >> Dockerfile
          echo "ENV BROKER_USERNAME \"everyone\"" >> Dockerfile
          echo "ENV BROKER_PASSWORD \"everyone\"" >> Dockerfile
          echo "ENV BROKER_PROTOCOL \"websockets\"" >> Dockerfile
          echo "ENV FLASK_HOST \"0.0.0.0\"" >> Dockerfile
          echo "ENV FLASK_PORT 8080" >> Dockerfile
          echo "ENV DOWNLOAD_WORKERS 8" >> Dockerfile
          echo "ENV SAVE_LOGS false" >> Dockerfile
          echo "ENV LOGS_DIR /app/logs" >> Dockerfile
          echo "RUN pip install pyopenssl --upgrade && pip install requests==2.26.0 urllib3==1.26.0" >> Dockerfile
          echo "RUN apt-get update && apt-get install -y cron gettext-base" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "RUN pip install wis2downloader" >> Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY ./docker/clean.py /app/clean.py" >> Dockerfile
          echo "COPY ./docker/clean.cron /etc/cron.d/clean.cron" >> Dockerfile
          echo "RUN chmod 0644 /etc/cron.d/clean.cron && crontab /etc/cron.d/clean.cron" >> Dockerfile
          echo "COPY ./docker/entrypoint.sh /entrypoint.sh" >> Dockerfile
          echo "RUN chmod +x /entrypoint.sh" >> Dockerfile
          echo 'ENTRYPOINT [ "/entrypoint.sh" ]' >> Dockerfile
          echo 'CMD ["wis2downloader","--config","/app/config.json"]' >> Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
